name: energy-calc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - dkh=1.2
  - gau2grid=2.0.7
  - gtest=1.14.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libecpint=1.0.7
  - libexpat=2.6.2
  - libffi=3.4.4
  - libint=2.9.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libpcm=1.2.3
  - libsqlite=3.45.2
  - libxc-c=6.2.2
  - libzlib=1.2.13
  - llvm-openmp=18.1.3
  - msgpack-python=1.0.7
  - ncurses=6.4
  - networkx=3.3
  - numpy=1.26.4
  - openssl=3.2.1
  - optking=0.2.1
  - pcmsolver=1.2.3
  - pint=0.23
  - pip=23.3.1
  - psi4=1.9.1
  - psutil=5.9.8
  - pugixml=1.14
  - py-cpuinfo=9.0.0
  - pybind11-abi=4
  - pydantic=2.7.0
  - pydantic-core=2.18.1
  - python=3.11.8
  - python_abi=3.11
  - pyyaml=6.0.1
  - qcelemental=0.27.1
  - qcengine=0.29.0
  - readline=8.2
  - scipy=1.13.0
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.13
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - debtcollector==3.0.0
      - grpcio==1.62.1
      - grpcio-tools==1.62.1
      - pillow==10.3.0
      - protobuf==4.25.3
      - psikit==0.2.0
      - rdkit==2023.9.5
      - wrapt==1.16.0
